Update sample 3 readme
Azure-Samples/active-directory-dotnetcore-daemon-v2 pull request #128
Opened 2021-12-17 01:45 UTC by v-michaelmi

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Follow the README file and comment on clarity/correctness

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* The README

## Other Information

2021-12-20 20:38 UTC, aremo-ms approved these changes

2021-12-20 23:29 UTC, v-michaelmi commented
@aremo-ms 

Very much so.

When the original script was run it would create a certificate and have it attributed to the application but it wouldn't exist in the Key Vault.

We could automate creating a Key Vault and uploading the certificate there directly. I ran it past @kalyankrishna1 but he said it might not be the best idea at the moment. We can discuss when he gets back.

2021-12-21 01:09 UTC, jmprieur commented on 3-Using-KeyVault/AppCreationScripts-withCert/Configure.ps1
> -   # Generate a certificate
I disagree with removing this code
Rather add instructions on how people can upload their certificate to KeyVault!

2021-12-21 01:10 UTC, jmprieur commented on 3-Using-KeyVault/README.md
> +* **NOTE:** The MSAL library uses the [DefaultAzureCredential Class](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) to access the certificates st
```suggestion
* **NOTE:** The MicrosoftIdentityWeb library uses the [DefaultAzureCredential Class](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) to access the certificates stored in your Key Vault. If you have multiple credentials being used on your machine it is possible that the incorrect credential will be used to access the Key Vault causing an error. See the [EnvironmentCredential Class](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet) for the list of environment variables to change to use the proper credentials when accessing the Key Vault. If you have Visual Studio instaled, you can set the Azure credentials used by this application by [following this guide](https://docs.microsoft.com/en-us/dotnet/azure/configure-visual-studio) and setting the **Azure Service Authentication** account as appropriate.
```

2021-12-21 13:38 UTC, aremo-ms commented on 3-Using-KeyVault/AppCreationScripts-withCert/Configure.ps1
> -   # Generate a certificate
> @aremo-ms
> 
> Very much so.
> 
> When the original script was run it would create a certificate and have it attributed to the application but it wouldn't exist in the Key Vault.
> 
> We could automate creating a Key Vault and uploading the certificate there directly. I ran it past @kalyankrishna1 but he said it might not be the best idea at the moment. We can discuss when he gets back.

@v-michaelmi 
It doesn't look right to me, sorry to say
We should have a way to create a KeyVault and add a certificate to it. 
I see we use certificate option in another samples, like 4-1. 
**I will investigate the option of KeyVault with certificate**

2021-12-21 19:51 UTC, v-michaelmi commented on 3-Using-KeyVault/AppCreationScripts-withCert/Configure.ps1
> -   # Generate a certificate
@jmprieur

I reverted the code and added some instruction for exporting the generated certificate as a **PFX** that can be uploaded to Azure. I'm hoping to find some Microsoft docs for users to reference using the export wizard from `certmgr` and will update when I can. We can also add some references for exporting with PowerShell (I didn't include that in the script because it requires password setting) but I want to keep this as linear as I can without burying the user with information.

2021-12-21 23:25 UTC, v-michaelmi commented on 3-Using-KeyVault/AppCreationScripts-withCert/Configure.ps1
> -   # Generate a certificate
@jmprieur 

After playing around with this I'm thinking the better path is to add in **PFX** generation within the `Configure.ps1` script and prompt the user for a password. Added in the steps for loading the generated PFX file to a Key Vault. Many ways to skin this cat. Hopefully left our users with the easiest.

2022-01-07 00:46 UTC, jmprieur commented
@v-michaelmi @aremo-ms : Is there a reason why we don't recommend to use the DefaultCertificateLoader?

2022-01-07 07:39 UTC, v-michaelmi commented
@jmprieur This sample does use the **DefaultCertificateLoader**. I can add in some additional documentation about how it works. I have a section letting the user know that they may need to update their default credentials to get it to work properly but it doesn't mention the  **DefaultCertificateLoader** by name. I can update this.

2022-01-07 18:27 UTC, aremo-ms commented
> 

@jmprieur We do use DefaultCertificateLoader [here](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/2bed49d566d6bdc5dfe015e3675c7a74e963f9dc/3-Using-KeyVault/daemon-console/Program.cs#L44)
Is your comment referring to documentation? I'm not sure I've got it right.

2022-01-07 19:23 UTC, jmprieur commented
@v-michaelmi @aremo-ms 
Yes, sorry, I was not clear. My question was about the README.md (I'm ashamed to say that I have not looked at the code :-))
Please update the doc

2022-01-07 22:09 UTC, v-michaelmi commented
@jmprieur 

No worries!

I added in a quick description of the `DefaultCertificateLoader`. I can update with links to more documentation for the loader itself as it becomes available.

2022-01-08 03:11 UTC, jmprieur commented on 3-Using-KeyVault/README.md
> +   This sample makes use of the **DefaultCertificateLoader** from the [Microsoft Identity Web](https://docs.microsoft.com/en-us/azure/active-directory/develop/microsoft-identity-web) library. If you'
```suggestion
   This sample makes use of the **DefaultCertificateLoader** from the [Microsoft Identity Web.Certificate](https://docs.microsoft.com/en-us/azure/active-directory/develop/microsoft-identity-web) library. If you've configured your application using the steps above the loader will retreive the certificate from the Key Vault as specified and store it within the `config` object. Accessing the certificate is discussed in more detail below.
```

2022-01-08 03:26 UTC, jmprieur commented
@v-michaelmi , LGTM

2022-01-10 19:26 UTC, jmprieur approved these changes
LGTM
Thanks @v-michaelmi

2022-01-13 01:52 UTC, kalyankrishna1 commented on 1-Call-MSGraph/AppCreationScripts-withCert/Cleanup.ps1
> +    Get-ChildItem -Path Cert:\CurrentUser\My | where { $_.subject -eq "CN=DaemonConsoleCert" } | Remove-Item
>Get-ChildItem -Path Cert:\CurrentUser\My | where { $_.subject -eq "CN=DaemonConsoleCert" } | Remove-Item [](http://example.com/codeflow?start=4&length=104)

was this missed from the code gen?

2022-01-13 01:53 UTC, kalyankrishna1 commented
> #### Register the client app (daemon-console)

These look out of date to me maybe?

---
Refers to: 1-Call-MSGraph/README.md:111 in 66becbe. [](commit_id = 66becbe4f296fb81e189a7ee81efe11f11931861, deletion_comment = False)

2022-01-13 03:09 UTC, kalyankrishna1 requested changes
:clock1:

2022-01-13 22:35 UTC, v-michaelmi commented on 1-Call-MSGraph/AppCreationScripts-withCert/Cleanup.ps1
> +    Get-ChildItem -Path Cert:\CurrentUser\My | where { $_.subject -eq "CN=DaemonConsoleCert" } | Remove-Item
This wasn't in the original code generator. I added this code in myself to streamline the user workflow.

2022-01-25 04:28 UTC, kalyankrishna1 commented on 3-Using-KeyVault/README.md
> +## Overview
[8:25 PM] Kalyan Krishna
remaining work is actually to simplify the 3-Using-KeyVault folder . To do so 

..delete all in this folder except the readme.md, and readmefiles. 

See my incomplete changes in this folder's readme, all you need to do is to tell the dev to use the solution in the first folder and make a few changes 

The readme should be just, create KV, upload cert, change some code and run the app. With another section highlighting the applicable code. 

Update the code in folder 1-> 1-Call-MSGraph and 2-> 2-Call-OwnApi with the extra code in chapter 3, so a developer can try the steps in #3 Readme with either of the earlier two. Leave PoP sample as is ..

Add an extra bit of code from BASHER (check with Alex) in #1 and #2. Essentially just print the tenant and app id after successful acquisition of the AT and call out specifically where approles (app permissions ) are checked with a line throwing an UnauthorizedException (403) if the app roles do not match. Highlight in "about the code " section as well

This will make the changes super simple to maintain.

2022-01-26 10:03 UTC, v-michaelmi commented
Bug update coming in.

Should cover just about everything we talked about @kalyankrishna1.

Only remaining piece is filtering out the tokens based on tenant issuer and app id. The only issue is that these values don't seem to exist on the token unless the application is configured to use the `common` Tenant value in the appsettings.json file.

I can set this up but I might need to make changes to the configure scripts.

Should we just punt that for now?

Otherwise, you should be able to run samples 1 and 2 with this update using the configure scripts, setting up a key vault with a certificate then configuring the app to use that certificate without issue.

2022-01-26 22:30 UTC, v-michaelmi commented
Disregard the last comment.

I'll have another update soon.

2022-01-27 00:28 UTC, aremo-ms commented
I cannot find SLN file under sample 3

2022-01-27 00:29 UTC, aremo-ms commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                var tid = jwt.Claims.FirstOrDefault(c => c.Type == "tid")?.Value;
try to use Microsoft.Identity.Web.ClaimConstants

2022-01-27 00:31 UTC, v-michaelmi commented
@aremo-ms 

It's gone now and by design.

The new flow is to be able to use the Key Vault from sample 1 and 2. I already added in the code (and explanations in the readme files for how to use it I believe).

You should be able to update the `appsettings.json` files to use key vaults and it _should_ 'just work'.

2022-01-27 00:32 UTC, v-michaelmi commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                var tid = jwt.Claims.FirstOrDefault(c => c.Type == "tid")?.Value;
If we ditch the `appid` constant check I'm alright with that.

2022-01-27 01:00 UTC, v-michaelmi commented
That last push should have everything.

There might be a few nits to pick-out but the high-level items are done and the **README** files should contain an explanation for everything.

2022-01-27 01:57 UTC, jmprieur reviewed
I would recommend to do a few changes

2022-01-27 01:57 UTC, jmprieur commented on 1-Call-MSGraph/daemon-console/AuthenticationConfig.cs
>          public string CertificateName { get; set; }
Why not use only the certificate description? 
The name of the certificate can be specified as well. See https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates#specifying-certificates

2022-01-27 01:57 UTC, jmprieur commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                    X509Certificate2 certificate = ReadCertificate(config.CertificateName);
That part is not needed.

2022-01-27 01:57 UTC, jmprieur commented on 1-Call-MSGraph/daemon-console/Program.cs
> +            await CallMSGraphUsingGraphSDK(app, scopes);
Maybe the other way around? I guess we want customers to use the Graph SDK.

2022-01-27 01:57 UTC, jmprieur commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                var jwt = (JwtSecurityToken)tokenHandler.ReadToken(result.AccessToken);
You cannot do that!
A client is not allowed to crack-open the access token (which could be encrypted).

@hpsin what would you recommend for a daemon app?

2022-01-27 01:57 UTC, jmprieur commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                var tid = jwt.Claims.FirstOrDefault(c => c.Type == "tid")?.Value;
and if you could crack open the token, there are two claims representing the tenant Id (see id.web GetTenantId())

2022-01-27 01:57 UTC, jmprieur commented on 1-Call-MSGraph/daemon-console/appsettings.json
> +  "CertificateName": "[Or instead of client secret: Enter here the name of a certificate (from the user cert store) as registered with your application]",
It's not enough to be in the certificate store (There is something implicit here).
Is it the user or machine cert store?

2022-01-27 01:57 UTC, jmprieur commented on 2-Call-OwnApi/daemon-console/AuthenticationConfig.cs
> +        /// <remarks>Holds all of the expected roles a token is to contain to have access to the application.
```suggestion
        /// <remarks>Holds all of the expected roles a token is expected to contain to have access to the application.
```

2022-01-27 16:32 UTC, hpsin commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                var jwt = (JwtSecurityToken)tokenHandler.ReadToken(result.AccessToken);
Just don't do this? I'm not sure it's needed, it's ahead of time debugging. 

You should know well before you ever request the token what the appid and tenant ID will be, because they're specified in the request that gives you the token.  So the appid and tenantId checks don't accomplish anything (but are nice to use for debugging). 

The roles check is understandable, since we don't have a scopes param in the response.  I wish we had a way to check your own roles in a tenant, but we don't yet.  I'd prefer that this code be omitted and filed as a blocker on either app model (for a lookup API) or ESTS (to append roles to the token response as an extension of the client credentials flow). 

The correct pattern here is to call the API, fail due to privileges, and then tell the user/admin to get this daemon additional roles.  It's ugly, but the only correct path forward today.

2022-01-27 18:52 UTC, v-michaelmi commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                var jwt = (JwtSecurityToken)tokenHandler.ReadToken(result.AccessToken);
@jmprieur @hpsin @kalyankrishna1 
 
It's definitely not needed to get the app to work.

I can revert this but maybe I misinterpreted a suggestion to print the **App ID** and **Tenant ID** (which you definitely don't need to extract from the JWT).
 
 Should we just bypass the roles check completely for now? It could be useful for developers to get their feet wet understanding how claims exist in JWT's but I definitely get where you guys are coming from where a lot of the best practices I've been reading seen to suggest "_Leave that JWT alone! Let Azure deal with it!_"
 
 I was working on this with the perspective of holding someone's hand to help give some context around "_Oh. That's how the app works and that's what JWT guts look like._" Otherwise you're right that it is preemptive debugging and overhead.

2022-01-27 18:54 UTC, v-michaelmi commented on 1-Call-MSGraph/daemon-console/appsettings.json
> +  "CertificateName": "[Or instead of client secret: Enter here the name of a certificate (from the user cert store) as registered with your application]",
The `configure.ps1` script places it in the user store. I'll add some clarity to the verbiage here.

2022-01-27 18:54 UTC, v-michaelmi commented on 1-Call-MSGraph/daemon-console/AuthenticationConfig.cs
>          public string CertificateName { get; set; }
I like that!

I'll patch this up.

2022-01-27 19:33 UTC, jmprieur commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                var jwt = (JwtSecurityToken)tokenHandler.ReadToken(result.AccessToken);
It's great that developers understand claims in JWTs, but this is for web APIs. not for client 
Our samples are copied/pasted everywhere. We cannot afford showing bad practices @v-michaelmi

2022-01-28 06:39 UTC, v-michaelmi commented
Updated with reversions of claims checks, refactoring to load certificates using `CertificateDescription` objects and documentation to explain how to load certificates using a `Certificate` property in the `apsettings.json` file.

@kalyankrishna1 I looked into loading `ClaimsPrincipals` from tokens instead of looking directly at the **JWT's** and the information is not there. We could use the `HttpContext` to get that information if we're willing to use an app builder for this.

It's not out of the question but considering how much this has blown up already I'm really thinking we should punt on that. The other task I'm working on to get some basic testing working leverages an ASP.NET `Host` builder so we can revisit it then.

Otherwise still have a few nits to deal with here that I'll get that done soon.

2022-01-28 06:42 UTC, v-michaelmi commented on 1-Call-MSGraph/AppCreationScripts/Configure.ps1
> -}
Replaced the logic here to use the built-in:

$dictionary | ConvertTo-Json | Out-File $configFile

2022-01-28 18:07 UTC, v-michaelmi commented on 1-Call-MSGraph/daemon-console/appsettings.json
> +  "CertificateName": "[Or instead of client secret: Enter here the name of a certificate (from the user cert store) as registered with your application]",
Removed with the last update.

2022-01-28 18:08 UTC, v-michaelmi commented on 1-Call-MSGraph/daemon-console/Program.cs
> +                    X509Certificate2 certificate = ReadCertificate(config.CertificateName);
Has since been removed.

2022-02-07 10:12 UTC, kalyankrishna1 approved these changes
:shipit:

2022-02-07 21:14 UTC, merged