Add basher
Azure-Samples/active-directory-dotnetcore-daemon-v2 pull request #140
Opened 2022-07-15 02:26 UTC by v-michaelmi

## Purpose

* This is meant to update the current `own-api` sample to distinguish between user and application provided tokens.
* A sample app was added similar to the [ctive-directory-aspnetcore-webapp-openidconnect-v2 4-1](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg) sample to show case hoe the API differentiates the tokens. Mostly meant for reference and discussion at this point.

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Documentation will follow. If you want to test the daemon and API create an application permission called `Todo.ReadWrite.All` and use that instead of the original `DaemonAppRole`. You will also need to enable the [idtyp](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims) optional claim. 

## What to Check
Verify that the following are valid
* Smoke test for now. Should run like before. If you're up for it you can also create an app for the `TodoList-WebApp` project. Just be sure to add `Todo.Read` and `Todo.Write` delegated permissions to the API in the Azure portal and add them to your `Scopes` section of the `appsettings.json` file.

## Other Information

2022-07-21 00:55 UTC, v-michaelmi commented
The `TodoList-WebApp` project was added to show case differences for when a request is made to the API with an `application` permission as opposed to an `delegated` permission.

Pretty much a facsimile of the [4-1 openid sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg). Can remove upon request.

2022-07-25 19:19 UTC, derisen commented on 2-Call-OwnApi/README.md
> +    }
1) should we give instructions via the UI instead, instead of editing the manifest?
2) should there be a Todo.Read.All scope as well? (to align with 4-1)

2022-07-25 19:26 UTC, derisen commented on 2-Call-OwnApi/README.md
>  > Note: if you used the setup scripts, the changes below will have been applied for you
Right above in instructions we still have `DaemonAppRole` -search&replace perhaps?

2022-07-25 19:28 UTC, v-michaelmi commented on 2-Call-OwnApi/README.md
> +    }
The ask from @kalyankrishna1 was to have on master **ReadWrite** permission but I can update this.

I'll put in some instructions for UI as well though.

2022-07-25 19:31 UTC, derisen commented on 2-Call-OwnApi/README.md
>  ### Step 4: Run the sample
Just for the folks running this through Visual Studio, can we configure the solution to start multiple projects when hit the start/f5 (web api, daemon)

2022-07-25 19:49 UTC, derisen commented on 2-Call-OwnApi/README.md
> +2. Find the app key `BaseUrl` in the `DownStreamApi` section and set to `https://localhost:44372`
```suggestion
2. Find the app key `BaseUrl` in the `DownStreamApi` section and set to `https://localhost:44372/`
```

2022-07-25 19:49 UTC, derisen commented on 2-Call-OwnApi/README.md
> +1. Find the app key `TenantId`  in the `AzureAd` section and replace the existing value with your Azure AD tenant name.
we don't have TenantId property currently in the appsetting.json

2022-07-25 19:55 UTC, derisen commented on 2-Call-OwnApi/TodoList-WebApi/Controllers/TodoController.cs
> +    private bool IsAppMakingRequest()
just a reminder to sync these method names with the 4-1 web api sample

2022-07-25 19:56 UTC, v-michaelmi commented on 2-Call-OwnApi/README.md
>  > Note: if you used the setup scripts, the changes below will have been applied for you
Not seeing it in there but Ill comb through again

2022-07-29 03:03 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> -  - office-ms-graph
The code gen seems to be messing up the entries needed for samples explorer to function. Please check for me as why did it drop the following bits from the header


languages:
  - csharp
products:
  - azure-active-directory
  - dotnet-core
  - office-ms-graph

[https://review.docs.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main#metadata-structure-for-yaml-front-matter](https://review.docs.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main#metadata-structure-for-yaml-front-matter)

2022-07-29 03:04 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +# A .NET Core daemon console application calling a custom Web API with its own identity
>custom [](http://example.com/codeflow?start=51&length=6)

"custom protected" (lets keep protected :))

2022-07-29 03:06 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +[![Build status](https://identitydivision.visualstudio.com/IDDP/_apis/build/status/AAD%20Samples/.NET%20client%20samples/ASP.NET%20Core%20Web%20App%20tutorial)](https://identitydivision.visualstudio.
>https://identitydivision.visualstudio.com/IDDP/_apis/build/status/AAD%20Samples/.NET%20client%20samples/ASP.NET%20Core%20Web%20App%20tutorial [](http://example.com/codeflow?start=17&length=141)

this ([https://identitydivision.visualstudio.com/IDDP/_apis/build/status/AAD%20Samples/.NET%20client%20samples/active-directory-dotnetcore-daemon-v2%20CI](https://identitydivision.visualstudio.com/IDDP/_apis/build/status/AAD%20Samples/.NET%20client%20samples/active-directory-dotnetcore-daemon-v2%20CI)) I believe is the right path , check with JM , if needed

2022-07-29 03:08 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
>  The app is a .NET Core console application that gets the list of "ToDos" from `TodoList-WebApi` project by using Microsoft Authentication Library for .NET ([MSAL.NET](https://aka.ms/msal-net)) to acq
>The [](http://example.com/codeflow?start=0&length=3)

pls add another line about "The Web API is protected with the platform using MIW blah blah blah"

2022-07-29 03:16 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +## Variation: daemon application using client credentials with certificates
>Variation [](http://example.com/codeflow?start=3&length=9)

lets move the variation after standard flow (using secrets) somewhere below

2022-07-29 03:16 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +![Scenario Image](./ReadmeFiles/topology.png)
This seems duplicate

2022-07-29 03:17 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +## Variation: daemon application using client credentials with certificates
>## [](http://example.com/codeflow?start=0&length=2)

add another # (###)

2022-07-29 03:22 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +## Setup the sample
>##  [](http://example.com/codeflow?start=0&length=3)

Please install the docs authoring pack and use the linter .. the md needs worok ([https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack))

2022-07-29 03:25 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +   .\AppCreationScripts-WtihCert\Configure.ps1
this section needs an update from the code gen

2022-07-29 03:26 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +#### (Optional) Create a self-signed certificate
>Create a self-signed certificate [](http://example.com/codeflow?start=16&length=32)

we'll bundle this section with the two above around certs and place it right after the primary flow (with secrets)

2022-07-29 03:39 UTC, kalyankrishna1 commented on 2-Call-OwnApi/AppCreationScripts/sample.json
>        "Id": "service",
>service [](http://example.com/codeflow?start=13&length=7)

@v-michaelmi , lets aim to keep the service def as similar to the other one we have for 4-1 ([https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/5d4d4b60db8675d01c3bac5fc436962f5a1ed560/4-WebApp-your-API/4-1-MyOrg/AppCreationScripts/sample.json](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/5d4d4b60db8675d01c3bac5fc436962f5a1ed560/4-WebApp-your-API/4-1-MyOrg/AppCreationScripts/sample.json)). @derisen FYI

2022-07-29 03:41 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +##### Get certificate from Key Vault
>Get certificate from Key Vault [](http://example.com/codeflow?start=6&length=30)

lets bundle keyvault steps separately and place them below the certs usage one, which themselves should be below the secret using section

2022-07-29 03:42 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
>  To run this sample, you'll need:
how did entire section slip so far below !

2022-07-29 03:43 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +#### About the alternate code
to be moved under "About the code" section below

2022-07-29 05:16 UTC, kalyankrishna1 commented
> services.AddOptions<DownstreamApiOptions>()

add one line comment stating this is where the API support is added

---
Refers to: 2-Call-OwnApi/daemon-console/Program.cs:24 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:18 UTC, kalyankrishna1 commented
>     "TenantId": "[Enter here the tenantID or domain name for your Azure AD tenant]",

use standard text for comments

---
Refers to: 2-Call-OwnApi/daemon-console/appsettings.json:4 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:19 UTC, kalyankrishna1 commented
>                 var clientSecretPlaceholderValue = "[Enter here a client secret for your application]";

I'll suggest we drop this and rely on azureAD options only

---
Refers to: 2-Call-OwnApi/daemon-console/Services/ConfidentialClientApplicationService.cs:30 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:20 UTC, kalyankrishna1 commented
>     public async Task<AuthenticationResult> GetAuthenticationResultAsync()

might consider renaming it to more verbatim one like GetAccessTokenForApi() maybe?

---
Refers to: 2-Call-OwnApi/daemon-console/Services/ConfidentialClientApplicationService.cs:61 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:20 UTC, kalyankrishna1 commented
> public class ConfidentialClientApplicationService : IConfidentialClientApplicationService

Please consider commenting heavily

---
Refers to: 2-Call-OwnApi/daemon-console/Services/ConfidentialClientApplicationService.cs:11 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:21 UTC, kalyankrishna1 commented
> public interface ITodoService

consider commenting heavily

---
Refers to: 2-Call-OwnApi/daemon-console/Services/ITodoService.cs:8 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:21 UTC, kalyankrishna1 commented
> public interface IUploadTodosService

nit: replace upload with "Post"


---
Refers to: 2-Call-OwnApi/daemon-console/Services/IUploadTodosService.cs:7 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:22 UTC, kalyankrishna1 commented
> public class TodoService : ITodoService

This needs extensive commenting

---
Refers to: 2-Call-OwnApi/daemon-console/Services/TodoService.cs:16 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:23 UTC, kalyankrishna1 commented
> public class UploadTodosService : IUploadTodosService

consider using "Post" or "Add" instead of "Upload"

---
Refers to: 2-Call-OwnApi/daemon-console/Services/UploadTodosService.cs:9 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:24 UTC, kalyankrishna1 commented
>         defaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", authenticationResult.AccessToken);

Explicitly and clearly call out that Access token for the API received from MSAL is added here to the request

---
Refers to: 2-Call-OwnApi/daemon-console/Services/TodoService.cs:132 in 8f4119e. [](commit_id = 8f4119e31779d3d64b2b5c0e332ed0e5f9f166ab, deletion_comment = False)

2022-07-29 05:24 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApp/TodoList-WebApp.csproj
> +  <PropertyGroup>
>PropertyGroup [](http://example.com/codeflow?start=3&length=13)

Lets drop this project and add a section in readme that points to 4-1 explaining that if the need is to sign-in a user, use that other sample

2022-07-29 05:26 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApp/Program.cs
> +builder.Services.AddMicrosoftIdentityWebAppAuthentication(builder.Configuration)
>AddMicrosoftIdentityWebAppAuthentication [](http://example.com/codeflow?start=17&length=40)

comment a lot :)

2022-07-29 05:30 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApp/Controllers/TodoController.cs
> +public class TodoController : Controller
>TodoController [](http://example.com/codeflow?start=13&length=14)

@v-michaelmi , We HAVE to use the 4-1 controller class as-is -> ([https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/5d4d4b60db8675d01c3bac5fc436962f5a1ed560/4-WebApp-your-API/4-1-MyOrg/TodoListService/Controllers/TodoListController.cs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/5d4d4b60db8675d01c3bac5fc436962f5a1ed560/4-WebApp-your-API/4-1-MyOrg/TodoListService/Controllers/TodoListController.cs)).
there is a lot to change here to accommodate it

2022-07-29 05:50 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApi/Program.cs
> +            .Bind(requiredTodoAccessPermissionsOptions));
what does this do?

2022-07-29 05:52 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApi/Services/TodoService.cs
> +public class TodoService : ITodoService
>TodoService [](http://example.com/codeflow?start=13&length=11)

need to use the new controller as instructed elsewhere

2022-07-29 10:01 UTC, kalyankrishna1 requested changes
:clock1:

2022-08-12 20:01 UTC, v-michaelmi commented on 2-Call-OwnApi/README.md
> +## Setup the sample
I'll go through the linter.

These are taken from the original README but I can update as per the linter.

2022-08-12 20:25 UTC, v-michaelmi commented on 2-Call-OwnApi/TodoList-WebApp/TodoList-WebApp.csproj
> +  <PropertyGroup>
Agreed. 👍

2022-08-12 20:28 UTC, v-michaelmi commented on 2-Call-OwnApi/TodoList-WebApi/Program.cs
> +            .Bind(requiredTodoAccessPermissionsOptions));
That binds the `RequiredTodoAccessPermissions` values you find in the `appsettings.json` file.

It makes it possible to access the values stored in the `appsettings.json` file within attributes in the `TodoController` like so:

```
    [HttpGet]
    [RequiredScopeOrAppPermission(
        RequiredScopesConfigurationKey = RequiredTodoAccessPermissionsOptions.RequiredDelegatedTodoReadClaimsKey,
        RequiredAppPermissionsConfigurationKey = RequiredTodoAccessPermissionsOptions.RequiredApplicationTodoReadWriteClaimsKey)]
    public IActionResult Get()
```

2022-08-12 21:14 UTC, v-michaelmi commented on 2-Call-OwnApi/TodoList-WebApp/Controllers/TodoController.cs
> +public class TodoController : Controller
I can get rid of the service and use a trivial dictionary to store to-do's for simplicity but this seems dated.

2022-08-12 21:57 UTC, v-michaelmi commented on 2-Call-OwnApi/TodoList-WebApp/Controllers/TodoController.cs
> +public class TodoController : Controller
Actually this will not work. Even with the new PR.

That sample sets the **Owner** property of **Todo's** to be the `ObjectId` of the incoming request which is going to be the `ObjectId` of the application making the call itself.

We'd to need to add another field to the To-do's that includes a 'UserId' or some other such field so that if an app wants to add Todo's associated with a user it can provide that user ID.

Otherwise, all TO-DO's written to that controller will have the application object id registered as **Owner**

2022-08-15 06:20 UTC, kalyankrishna1 commented
>   "Sample": {

add language and products tags

---
Refers to: 2-Call-OwnApi/AppCreationScripts/sample.json:2 in 6618021. [](commit_id = 66180215b1b5add5a7768c933dda97d52139b965, deletion_comment = False)

2022-08-15 06:21 UTC, kalyankrishna1 commented
>   "Sample": {

add language and products tags

---
Refers to: 2-Call-OwnApi/AppCreationScripts-withCert/sample.json:2 in 6618021. [](commit_id = 66180215b1b5add5a7768c933dda97d52139b965, deletion_comment = False)

2022-08-17 23:40 UTC, v-michaelmi commented on 2-Call-OwnApi/README.md
> +    }
@kalyankrishna1 got back to me and wanted the **Read.All** permission set.

Included with latest commit.

2022-09-06 03:02 UTC, kalyankrishna1 commented on 2-Call-OwnApi/daemon-console/Options/AzureAdOptions.cs
> +    public class AzureAdOptions : ConfidentialClientApplicationOptions
>AzureAdOptions [](http://example.com/codeflow?start=17&length=14)

We should no longer need this class as MIW implicitly takes care of it

2022-09-06 03:03 UTC, kalyankrishna1 commented on 2-Call-OwnApi/daemon-console/Options/DownStreamApiOptions.cs
> +    public class DownstreamApiOptions
>DownstreamApiOptions [](http://example.com/codeflow?start=17&length=20)

check if we need this class anymore

2022-09-06 03:04 UTC, kalyankrishna1 commented on 2-Call-OwnApi/daemon-console/Services/AccessTokienHandler.cs
> +public class AccessTokenHandler : DelegatingHandler
>AccessTokenHandler [](http://example.com/codeflow?start=13&length=18)

classes like this makes the job the protecting with MIW a tall and difficult job. We should aim for just the most basic thats needed for a developer to succeed.

2022-09-06 03:05 UTC, kalyankrishna1 commented on 2-Call-OwnApi/daemon-console/Services/IDataDisplayService.cs
> +public interface IDataDisplayService
>IDataDisplayService [](http://example.com/codeflow?start=17&length=19)

what benefit dies it offer over IToDoService?? again, trying to make a case for simpler code first

2022-09-06 03:08 UTC, kalyankrishna1 commented on 2-Call-OwnApi/ReadmeFiles/ReadmeAzureDeploy.md
> + <summary>Expand the section</summary>
>Expand [](http://example.com/codeflow?start=10&length=6)

This should now be generated by the codegen itself. See if we can get rid of this extra md file

2022-09-06 03:09 UTC, kalyankrishna1 commented on 2-Call-OwnApi/ReadmeFiles/ReadmeLearnMore.md
> +## Community Help and Support
move any specific section for .net+webapi+miw in the codegen and get rid of this file

2022-09-06 03:09 UTC, kalyankrishna1 commented on 2-Call-OwnApi/ReadmeFiles/ReadmeSetup.md
> +### (Optional) use the automation script
>automation [](http://example.com/codeflow?start=23&length=10)

no freakin way this section will ever not come from code gen :)

2022-09-06 03:10 UTC, kalyankrishna1 commented on 2-Call-OwnApi/ReadmeFiles/ReadmeUsingTheSample.md
> +To run this sample, you'll need:
>sample [](http://example.com/codeflow?start=12&length=6)

no freakin way this section will ever not come from code gen :)

2022-09-06 03:13 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApi/appsettings.json
> +    "RequiredApplicationTodoReadClaims": "Todo.Read.All Todo.ReadWrite.All",
>RequiredApplicationTodoReadClaims [](http://example.com/codeflow?start=5&length=33)

this is not scalable! 
say if one has a permission set of 100s. lets move this to individual constant string on top of the controller and show devs that they can make whatever combination they like on top of a controller method for the 'RequiredScopeOrAppPermission' attribute

2022-09-06 03:14 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApi/Program.cs
> +        builder.Configuration.GetSection(RequiredTodoAccessPermissionsOptions.RequiredTodoAccessPermissions)
we should avoid complexity when showcasing the power of the SDK. We need to show that the RequiredScopeOrAppPermission and AddMicrosoftIdentityWebApi() are powerful enough to deliver all thats needed and I'm very hesitatnt of code that makes this job of protecting web API any more complicated than it should be :)

2022-09-06 03:18 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApi/Services/TodoService.cs
> +    public IEnumerable<Todo> GetTodos(bool hasAppPermissions, Guid userIdentifier)
>bool hasAppPermissions [](http://example.com/codeflow?start=38&length=22)

this is derived and should not be passed as a param at all, as its a bad pattern. See 4-1 controller for how its done there

2022-09-06 03:19 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApi/Options/RequiredTodoAccessPermissionsOptions.cs
> +public class RequiredTodoAccessPermissionsOptions
>RequiredTodoAccessPermissionsOptions [](http://example.com/codeflow?start=13&length=36)

again, incredibly hesitant about adding unnecessary complexity, when none is required

2022-09-06 03:30 UTC, kalyankrishna1 commented on 2-Call-OwnApi/TodoList-WebApi/Options/RequiredTodoAccessPermissionsOptions.cs
> +    public const string RequiredDelegatedTodoWriteClaimsKey =
>RequiredDelegatedTodoWriteClaimsKey [](http://example.com/codeflow?start=24&length=35)

TBH, this is unnecessarily over-engineered to pick a string from a config file :)

2022-09-06 18:17 UTC, v-michaelmi commented
Trimming scope here.

See branch `2-basher` for newest

2022-09-06 18:17 UTC, closed without merging