Added controller from 4-1 sample.
Azure-Samples/active-directory-dotnetcore-daemon-v2 pull request #141
Opened 2022-09-06 18:19 UTC by v-michaelmi

## Purpose

* Add BASHER to sample 2

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Smoke test that sample works same as before.
* Also smoke test permissions where app access flow works correctly.

## What to Check
Verify that the following are valid
* Smoke test sample.
* See if compatible with sample `4-1`

## Other Information

2022-09-14 06:10 UTC, kalyankrishna1 requested changes
:clock1:

2022-12-15 22:14 UTC, derisen commented on 2-Call-OwnApi/AppCreationScripts/sample.json
> +      "SettingKind": "Text",
It's safer to use "SettingKind": "Replace" and then

```json
        {
          "key": "Enter_here_client secret_for_your_application",
          "value": ".AppKey"
        },
```

2022-12-15 22:20 UTC, derisen commented on 2-Call-OwnApi/README.md
> +    1. In the **Redirect URI** section enter the following redirect URI:
reminder: no redirect uri here

2022-12-15 22:26 UTC, derisen commented on 2-Call-OwnApi/README.md
> +### (Optional) Create a self-signed certificate
probably better to just link to README-use-certificate.md here

2023-01-23 20:11 UTC, derisen commented on 2-Call-OwnApi/README.md
> +    1. Since this app signs-in as itself using the [OAuth 2\.0 client credentials flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow), we will now proce
indentation/ordering here looks off

2023-01-23 20:13 UTC, derisen commented on 2-Call-OwnApi/README.md
> +1. In the **Overview** blade, find and note the **Application (client) ID**. You use this value in your app's configuration file(s) later in your code.
Are we missing redirect URI instructions?

2023-01-23 20:15 UTC, v-michaelmi commented on 2-Call-OwnApi/README.md
> +    1. Since this app signs-in as itself using the [OAuth 2\.0 client credentials flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow), we will now proce
No that's right. But yes that syntax is funky looking

![image](https://user-images.githubusercontent.com/93682173/214140691-6b380e32-8606-4e8f-b30d-493962fc2277.png)

2023-01-23 20:15 UTC, derisen commented on 2-Call-OwnApi/README.md
> +### (Optional) Create a self-signed certificate
This looks repetitive now that we have the same instructions in README-use-certificate

2023-01-23 20:16 UTC, derisen commented on 2-Call-OwnApi/README.md
> +1. In the **Overview** blade, find and note the **Application (client) ID**. You use this value in your app's configuration file(s) later in your code.
never mind, this is client credentials

2023-01-23 20:16 UTC, v-michaelmi commented on 2-Call-OwnApi/README.md
> +1. In the **Overview** blade, find and note the **Application (client) ID**. You use this value in your app's configuration file(s) later in your code.
Not in this case.

Daemon's don't have redirect URL's (they use the credential flow). We used to have an empty nonsense URL here like `https://daemon` but it did nothing.

2023-01-23 20:26 UTC, derisen commented on 2-Call-OwnApi/README.md
> +    1. Since this app signs-in as itself using the [OAuth 2\.0 client credentials flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow), we will now proce
Not that part though, I was talking about this and after:

> Since this app signs-in as itself using the [OAuth 2\.0 client credentials flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow), we will now proceed to select **application permissions**, which is required by apps authenticating as themselves.

2023-01-23 20:28 UTC, derisen commented on 2-Call-OwnApi/README-use-certificate.md
> +
Missing manual steps for cert generation using PowerShell here (looks like codegen didn't generate this so I'll open a bug there)

2023-01-23 20:39 UTC, kalyankrishna1 commented
Remove AppCreationScripts-withCert folder altogether

2023-01-23 20:46 UTC, kalyankrishna1 commented on 2-Call-OwnApi/AppCreationScripts-withCert/AppCreationScripts.md
>  ## Overview
>Overview [](http://example.com/codeflow?start=3&length=8)

delete all in this folder

2023-01-23 20:47 UTC, kalyankrishna1 commented on 2-Call-OwnApi/AppCreationScripts/sample.json
>    "Sample": {
>Sample [](http://example.com/codeflow?start=3&length=6)

code gen throws the following error

Application TodoList-webapi-daemon-v2 is missing the SDK field. Please specify the SDK that the app leverages. A list of valid values are: UnSpecified MicrosoftIdentityWeb MsalNet MsalJs MsalAngular MsalReact MsalPython MsalJava MsalNode

2023-01-23 21:07 UTC, derisen commented on 2-Call-OwnApi/README-use-certificate.md
> +</details>
```suggestion
<details>
<summary>Click here to use Powershell</summary>

To generate a new self-signed certificate, we will use the [New-SelfSignedCertificate](https://docs.microsoft.com/powershell/module/pki/new-selfsignedcertificate) Powershell command.

Open PowerShell and run the command with the following parameters to create a new self-signed certificate that will be stored in the **current user** certificate store on your computer:

```PowerShell
$cert = New-SelfSignedCertificate -Subject "CN=daemon-console-v2" -CertStoreLocation "Cert:\CurrentUser\My" -KeyExportPolicy Exportable -KeySpec Signature -KeyLength 2048 -KeyAlgorithm RSA -HashAlgorithm SHA256
```

You can now export a public key (*.cer* file) and a public + private key combination (*.pfx* file) to use in your app:

```Powershell
Export-Certificate -Cert $cert -FilePath "C:\Users\diego\Desktop\\daemon-console-v2.cer" ## Specify your preferred location

$mypwd = ConvertTo-SecureString -String "{myPassword}" -Force -AsPlainText  ## Replace {myPassword}
Export-PfxCertificate -Cert $cert -FilePath "C:\Users\diego\Desktop\\daemon-console-v2.pfx" -Password $mypwd ## Specify your preferred location
```

Proceed to [Step 2](#configure-an-azure-ad-app-registration-to-use-a-certificate).

> :information_source: For more details, follow the guide: [Create a self-signed public certificate to authenticate your application](https://learn.microsoft.com//azure/active-directory/develop/howto-create-self-signed-certificate)

</details>
```

2023-01-23 21:09 UTC, derisen commented on 2-Call-OwnApi/README-use-certificate.md
> +</details>
```suggestion
<details>
<summary>Click here to use Powershell</summary>

To generate a new self-signed certificate, we will use the [New-SelfSignedCertificate](https://docs.microsoft.com/powershell/module/pki/new-selfsignedcertificate) Powershell command.

Open PowerShell and run the command with the following parameters to create a new self-signed certificate that will be stored in the **current user** certificate store on your computer:

```PowerShell
$cert = New-SelfSignedCertificate -Subject "CN=daemon-console-v2" -CertStoreLocation "Cert:\CurrentUser\My" -KeyExportPolicy Exportable -KeySpec Signature -KeyLength 2048 -KeyAlgorithm RSA -HashAlgorithm SHA256
```

You can now export a public key (*.cer* file) and a public + private key combination (*.pfx* file) to use in your app:

```Powershell
Export-Certificate -Cert $cert -FilePath "C:\Users\diego\Desktop\\daemon-console-v2.cer" ## Specify your preferred location

$mypwd = ConvertTo-SecureString -String "{myPassword}" -Force -AsPlainText  ## Replace {myPassword}
Export-PfxCertificate -Cert $cert -FilePath "C:\Users\diego\Desktop\\daemon-console-v2.pfx" -Password $mypwd ## Specify your preferred location
```

Proceed to [Step 2](#configure-an-azure-ad-app-registration-to-use-a-certificate).

> :information_source: For more details, follow the guide: [Create a self-signed public certificate to authenticate your application](https://learn.microsoft.com//azure/active-directory/develop/howto-create-self-signed-certificate)

</details>
```

2023-01-23 21:11 UTC, kalyankrishna1 commented on 2-Call-OwnApi/README.md
> +1. Find the key `CertificateName` and replace the existing value with Certificate.
>CertificateName [](http://example.com/codeflow?start=17&length=15)

So this will either be a "secret" or a "certificate" as key, need to look into codegen maybe for this?

2023-01-23 21:13 UTC, kalyankrishna1 commented on 2-Call-OwnApi/AppCreationScripts/sample.json
> +      "Sdk": "MicrosoftIdentityWeb",
>MicrosoftIdentityWeb [](http://example.com/codeflow?start=14&length=20)

MsalNet?

2023-01-24 03:07 UTC, jmprieur commented on 2-Call-OwnApi/daemon-console/Program.cs
> +            services.Configure<MicrosoftAuthenticationOptions>(
This is no longer needed!

2023-01-24 03:07 UTC, jmprieur commented on 2-Call-OwnApi/daemon-console/Program.cs
> +                    .AddInMemoryTokenCaches();
This is no longer needed (default)

2023-04-27 22:08 UTC, v-michaelmi commented
Obsolete.

Closing.

2023-04-27 22:08 UTC, closed without merging