Lozensky/managed id sample
Azure-Samples/active-directory-dotnetcore-daemon-v2 pull request #187
Opened 2024-02-20 22:38 UTC by JoshLozensky

## Purpose
Adds sample for using managed identity to call an api.

2024-02-21 23:56 UTC, jmprieur requested changes
A few things to change.
Also no need for the images. None match the scenario

2024-02-21 23:56 UTC, jmprieur commented on 5-Call-MSGraph-ManagedIdentity/README.md
> +#### Register the client app (daemon-console)
Instead of this section, you need to add access to Microsoft Graph from your managed identity.
See https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-app?tabs=azure-powershell#grant-access-to-microsoft-graph

2024-02-21 23:56 UTC, jmprieur commented on 5-Call-MSGraph-ManagedIdentity/README.md
> +
from here to Step 3 included, you can remove

2024-02-21 23:56 UTC, jmprieur commented on 5-Call-MSGraph-ManagedIdentity/README.md
> +### The code to protect the Web API
All this section is wrong. Do you think it looks like the code in Program.cs?

2024-02-22 03:02 UTC, jennyf19 commented on 5-Call-MSGraph-ManagedIdentity/daemon-console/Daemon-Console.csproj
> +		<TargetFramework>net7.0</TargetFramework>
>net7.0 [](http://example.com/codeflow?start=19&length=6)

net8.0

2024-02-22 03:06 UTC, jennyf19 commented on 5-Call-MSGraph-ManagedIdentity/daemon-console/Program.cs
> +using Microsoft.Identity.Web;
remove unused usings

2024-02-22 03:07 UTC, jennyf19 commented on 5-Call-MSGraph-ManagedIdentity/daemon-console/Program.cs
> +    /// This sample shows how to query the Microsoft Graph from a daemon application
>application [](http://example.com/codeflow?start=73&length=11)

maybe add "using Managed Identity." remember to add a "." at the end.

2024-02-22 03:09 UTC, jennyf19 commented on 5-Call-MSGraph-ManagedIdentity/daemon-console/Program.cs
> +                    .GetAsync(r => r.Options.WithAppOnly());
I think this is in the doc JM wrote too?

2024-02-22 03:10 UTC, jennyf19 commented on 5-Call-MSGraph-ManagedIdentity/README.md
> +description: "Shows how a daemon console app uses a managed identity to get an access token and call a protected Web API with the Microsoft.Identity.Web library."
>W [](http://example.com/codeflow?start=113&length=1)

lowercase

2024-02-22 03:12 UTC, jennyf19 commented on 5-Call-MSGraph-ManagedIdentity/README.md
> +#### Choose the Azure AD tenant where you want to create your applications
>Azure AD [](http://example.com/codeflow?start=16&length=8)

EntraID

2024-02-23 21:45 UTC, jennyf19 approved these changes
:shipit:

2024-03-05 00:08 UTC, jmprieur approved these changes
LGTM
Thanks @JoshLozensky

2024-03-05 00:09 UTC, merged